### ISSUE TITLE
What relays is this code made for?

### ISSUE THREAD

**Issue by sashaFedchuk** [doleron/esp8266-1-channel-relay-board-with-mqtt#3]
This code is made for such [ralay x4 ](https://ru.aliexpress.com/item/32965886110.html?cv=47843&af=501872&mall_affr=pr3&afref=https%253A%252F%252Fa.empyeria.me%252Fitem%252F32965886110&dp=dc560a0a9cac6dc5ea18d688db5e1fad&scm=1007.22893.125779.0&pvid=5a1b058b-bd74-4d28-86c9-96c965d7c17a&onelink_thrd=0.0&onelink_page_from=ITEM_DETAIL&onelink_item_to=32965886110&onelink_duration=0.839023&onelink_status=noneresult&onelink_item_from=32965886110&onelink_page_to=ITEM_DETAIL&aff_platform=aaf&cpt=1563717721454&sk=VnYZvQVf&aff_trace_key=2de79487aa344c95b126e2f004644832-1563717721454-03578-VnYZvQVf&terminal_id=cfbc851d65f64d849538e944a6f2a926)

**Comment by doleron** [comment]
Sorry but I can't confirm it for you because the only model I have used has been the one in the picture in Readme.rd. Maybe @sehraf can provide any clue about that since he has worked with multichannel relays from this brand.

**Comment by sashaFedchuk** [comment]
Thanks!

**Comment by sehraf** [comment]
yes, it works with this four channel model, too (i am using the same)

**Comment by doleron** [comment]
Thank you @sehraf
