### ISSUE TITLE
Reading command execution

### ISSUE THREAD

**Issue by markunca** [doleron/esp8266-1-channel-relay-board-with-mqtt#4]
Hi,
trying to get feedback from esp - read pin to be sure, that it was executed, but currently with any luck. Any tip?

code looks like this:

```
`statepin3=digitalRead(pin3);
      if(statepin3==HIGH){
        client.publish("outside_carpet/feedback/3", "1");
        Serial.println("PIN 3 HIGH");
      }
      else{
        client.publish("outside_carpet/feedback/3", "0");
        Serial.println("PIN 3 LOW");
      }`
```

**Comment by doleron** [comment]
Not clear what is the problem your are facing. Can you explain what is the expected behaviour and what is the wrong behaviour you are experiencing?

**Comment by markunca** [comment]
My current problem - using homebridge to automate my home. This relay should turn on/off heating of garage. Currently in test period when I execute command from mqtt it is send to esp, but not every time command from mqtt is changing relay to on or off. Command is receive from esp but not executed. I need some method which will periodically find out and send from esp current relay status to mqtt based on which will homebridge try to turn it on/off again until it will succeed.

**Comment by doleron** [comment]
Ok, I got it. I'm afraid that by default the relay board doesn't expose the relay status. I think that reading ESP pin will fail to provide a clue about the relay actual position. If you really need to know the relay status (yes, this is actually required in setups like yours), I think that the way to go is by updating the program running inside MCU 15f104W. One point caught my attention is the scenario when the relay refuses to change even after receive a command. Or your board have a problem or you are facing a PSU issue. Furthermore, make sure the load you are using with this relay is compatible and always use some sort of electrical protection to open the circuit automatically in dare situations.
